// protoc --go_out=. --go-grpc_out=. api/grpc/v1/orders.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: api/grpc/v1/orders.proto

package orders_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_api_grpc_v1_orders_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_orders_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_orders_proto_rawDescGZIP(), []int{0}
}

func (x *GetOrderRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderResponse) Reset() {
	*x = GetOrderResponse{}
	mi := &file_api_grpc_v1_orders_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse) ProtoMessage() {}

func (x *GetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_orders_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse.ProtoReflect.Descriptor instead.
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_orders_proto_rawDescGZIP(), []int{1}
}

func (x *GetOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type Order struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Number           int32                  `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	TotalCost        int32                  `protobuf:"varint,3,opt,name=totalCost,proto3" json:"totalCost,omitempty"`
	CreatedDate      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=createdDate,proto3" json:"createdDate,omitempty"`
	LastModifiedDate *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=lastModifiedDate,proto3" json:"lastModifiedDate,omitempty"`
	Status           int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	Products         []*Product             `protobuf:"bytes,7,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_api_grpc_v1_orders_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_orders_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_orders_proto_rawDescGZIP(), []int{2}
}

func (x *Order) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Order) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Order) GetTotalCost() int32 {
	if x != nil {
		return x.TotalCost
	}
	return 0
}

func (x *Order) GetCreatedDate() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedDate
	}
	return nil
}

func (x *Order) GetLastModifiedDate() *timestamppb.Timestamp {
	if x != nil {
		return x.LastModifiedDate
	}
	return nil
}

func (x *Order) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Order) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	PurchasePrice int32                  `protobuf:"varint,5,opt,name=purchasePrice,proto3" json:"purchasePrice,omitempty"`
	SalePrice     int32                  `protobuf:"varint,6,opt,name=salePrice,proto3" json:"salePrice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_api_grpc_v1_orders_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_orders_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_orders_proto_rawDescGZIP(), []int{3}
}

func (x *Product) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Product) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Product) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetPurchasePrice() int32 {
	if x != nil {
		return x.PurchasePrice
	}
	return 0
}

func (x *Product) GetSalePrice() int32 {
	if x != nil {
		return x.SalePrice
	}
	return 0
}

type GetOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersResponse) Reset() {
	*x = GetOrdersResponse{}
	mi := &file_api_grpc_v1_orders_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersResponse) ProtoMessage() {}

func (x *GetOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_orders_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersResponse.ProtoReflect.Descriptor instead.
func (*GetOrdersResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_orders_proto_rawDescGZIP(), []int{4}
}

func (x *GetOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

var File_api_grpc_v1_orders_proto protoreflect.FileDescriptor

const file_api_grpc_v1_orders_proto_rawDesc = "" +
	"\n" +
	"\x18api/grpc/v1/orders.proto\x12\bproto.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"!\n" +
	"\x0fGetOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"9\n" +
	"\x10GetOrderResponse\x12%\n" +
	"\x05order\x18\x01 \x01(\v2\x0f.proto.v1.OrderR\x05order\"\x9a\x02\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06number\x18\x02 \x01(\x05R\x06number\x12\x1c\n" +
	"\ttotalCost\x18\x03 \x01(\x05R\ttotalCost\x12<\n" +
	"\vcreatedDate\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vcreatedDate\x12F\n" +
	"\x10lastModifiedDate\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x10lastModifiedDate\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12-\n" +
	"\bproducts\x18\a \x03(\v2\x11.proto.v1.ProductR\bproducts\"\xa1\x01\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12$\n" +
	"\rpurchasePrice\x18\x05 \x01(\x05R\rpurchasePrice\x12\x1c\n" +
	"\tsalePrice\x18\x06 \x01(\x05R\tsalePrice\"<\n" +
	"\x11GetOrdersResponse\x12'\n" +
	"\x06orders\x18\x01 \x03(\v2\x0f.proto.v1.OrderR\x06orders2\x93\x01\n" +
	"\fOrderService\x12@\n" +
	"\tGetOrders\x12\x16.google.protobuf.Empty\x1a\x1b.proto.v1.GetOrdersResponse\x12A\n" +
	"\bGetOrder\x12\x19.proto.v1.GetOrderRequest\x1a\x1a.proto.v1.GetOrderResponseB\x18Z\x16pkg/grpc/v1/orders_apib\x06proto3"

var (
	file_api_grpc_v1_orders_proto_rawDescOnce sync.Once
	file_api_grpc_v1_orders_proto_rawDescData []byte
)

func file_api_grpc_v1_orders_proto_rawDescGZIP() []byte {
	file_api_grpc_v1_orders_proto_rawDescOnce.Do(func() {
		file_api_grpc_v1_orders_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_grpc_v1_orders_proto_rawDesc), len(file_api_grpc_v1_orders_proto_rawDesc)))
	})
	return file_api_grpc_v1_orders_proto_rawDescData
}

var file_api_grpc_v1_orders_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_grpc_v1_orders_proto_goTypes = []any{
	(*GetOrderRequest)(nil),       // 0: proto.v1.GetOrderRequest
	(*GetOrderResponse)(nil),      // 1: proto.v1.GetOrderResponse
	(*Order)(nil),                 // 2: proto.v1.Order
	(*Product)(nil),               // 3: proto.v1.Product
	(*GetOrdersResponse)(nil),     // 4: proto.v1.GetOrdersResponse
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 6: google.protobuf.Empty
}
var file_api_grpc_v1_orders_proto_depIdxs = []int32{
	2, // 0: proto.v1.GetOrderResponse.order:type_name -> proto.v1.Order
	5, // 1: proto.v1.Order.createdDate:type_name -> google.protobuf.Timestamp
	5, // 2: proto.v1.Order.lastModifiedDate:type_name -> google.protobuf.Timestamp
	3, // 3: proto.v1.Order.products:type_name -> proto.v1.Product
	2, // 4: proto.v1.GetOrdersResponse.orders:type_name -> proto.v1.Order
	6, // 5: proto.v1.OrderService.GetOrders:input_type -> google.protobuf.Empty
	0, // 6: proto.v1.OrderService.GetOrder:input_type -> proto.v1.GetOrderRequest
	4, // 7: proto.v1.OrderService.GetOrders:output_type -> proto.v1.GetOrdersResponse
	1, // 8: proto.v1.OrderService.GetOrder:output_type -> proto.v1.GetOrderResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_grpc_v1_orders_proto_init() }
func file_api_grpc_v1_orders_proto_init() {
	if File_api_grpc_v1_orders_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_grpc_v1_orders_proto_rawDesc), len(file_api_grpc_v1_orders_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_grpc_v1_orders_proto_goTypes,
		DependencyIndexes: file_api_grpc_v1_orders_proto_depIdxs,
		MessageInfos:      file_api_grpc_v1_orders_proto_msgTypes,
	}.Build()
	File_api_grpc_v1_orders_proto = out.File
	file_api_grpc_v1_orders_proto_goTypes = nil
	file_api_grpc_v1_orders_proto_depIdxs = nil
}
